---
- name: Import authority trust establishment tasks
  ansible.builtin.import_tasks: establish-authorities.yml

- name: Import host certificate signing tasks
  ansible.builtin.import_tasks: sign-host-keys.yml
  when: sshd_hostca_key_file is defined

- name: Deploy arbitrary drop-in configurations
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "/etc/ssh/sshd_config.d/{{ item.name }}"
    validate: "{{ __sshd_binary }} -t -f %s"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ sshd_config_dropins }}"
  notify: restart sshd
  when: sshd_config_dropins is defined

- name: Flush SSHd Handlers
  ansible.builtin.meta: flush_handlers
