---
- name: Import host certificate signing tasks
  ansible.builtin.import_tasks: sign-host-keys.yml

#- name: Modify drop-in configurations
#  ansible.builtin.copy:
#    content: "{{ lookup(item.content, 'template') }}"
#    state: "{{ item.state }}"
#    path: "/etc/ssh/sshd_config.d/{item.name}"
#  loop: "{{ ssh_config_dropins }}"

#- name: Install userkey certificate authority
#  ansible.builtin.copy:
#    content: