---
- name: Enumerate host public keys
  ansible.builtin.find:
    paths: /etc/ssh/
    patterns: ssh_host_*_key.pub
  register: ssh_public_keys

- name: Copy remote public key
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "{{ sshd_local_working_directory }}/"
    flat: true
  with_items: "{{ ssh_public_keys.files }}"

- name: Display host principals
  ansible.builtin.debug:
    var: sshd_hostca_host_principals

#! This does not work with passphrase protected private keys.
#? Feature request: https://github.com/ansible-collections/community.crypto/issues/195
# - name: Sign host public keys
#   delegate_to: localhost
#   become: false
#   with_items: "{{ ssh_public_keys.files }}"
#   vars:
#     certificate_name: "{{ (item.path | basename | split('.'))[0] }}-cert.pub"
#   community.crypto.openssh_cert:
#     path: "{{ sshd_local_working_directory }}/{{ certificate_name }}"
#     signing_key: "{{ sshd_hostca_key_file }}"
#     public_key: "{{ sshd_local_working_directory }}/{{ item.path | basename }}"
#     identifier: "{{ sshd_hostca_host_identity }}"
#     principals: "{{ sshd_hostca_host_principals }}"
#     valid_from: -1h
#     valid_to: +52w
#     state: present
#     type: host

- name: "Sign SSH Public Keys."
  delegate_to: localhost
  ansible.builtin.expect:
    command: | #? The keygen will store the certfile with the key being signed
      ssh-keygen -s "{{ sshd_hostca_key_file }}"
        -I "{{ sshd_hostca_host_identity }}"
        -h -n "{{ sshd_hostca_host_principals }}"
        "{{ host_public_ssh_key_path  }}"
    responses:
      (?i)passphrase: "{{ sshd_hostca_key_passphrase }}"
  become: false
  no_log: true
  with_items: "{{ ssh_public_keys.files }}"
  vars:
    #certificate_filename: "{{ (item.path | basename | split('.'))[0] }}-cert.pub"
    #certificate_path: "{{ sshd_local_working_directory }}/{{ certificate_filename }}"
    host_public_ssh_key_path: "{{ sshd_local_working_directory }}/{{ item.path | basename }}"

- name: Enmerate host certificates
  delegate_to: localhost
  become: false
  ansible.builtin.find:
    paths: "{{ sshd_local_working_directory }}"
    patterns: ssh_host_*_key-cert.pub
  register: ssh_certificates

- name: Copy host certificates to host
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/etc/ssh/{{ item.path | basename }}"
    mode: "0644"
  with_items: "{{ ssh_certificates.files }}"
  notify: restart sshd

- name: Template HostCertificate configuration drop-in
  ansible.builtin.copy:
    content: |
      # -{ Ansible managed }--------------------------------------------------------
      # /etc/ssh/sshd_config.d/100-ansible-hostcas.conf - Configure trusted user CAs
      {% for certificate_file in ssh_certificates.files %}
      HostCertificate /etc/ssh/{{ certificate_file.path | basename }}
      {% endfor %}
    dest: /etc/ssh/sshd_config.d/100-ansible-hostcas.conf
    owner: root
    group: root
    mode: "0600"
  notify: restart sshd
